// Code generated by MockGen. DO NOT EDIT.
// Source: vcs.go
//
// Generated by this command:
//
//	mockgen -source=vcs.go -destination=mock/vcs_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/uber/submitqueue/runway/entity"
	vcs "github.com/uber/submitqueue/runway/extension/vcs"
	gomock "go.uber.org/mock/gomock"
)

// MockVCS is a mock of VCS interface.
type MockVCS struct {
	ctrl     *gomock.Controller
	recorder *MockVCSMockRecorder
	isgomock struct{}
}

// MockVCSMockRecorder is the mock recorder for MockVCS.
type MockVCSMockRecorder struct {
	mock *MockVCS
}

// NewMockVCS creates a new mock instance.
func NewMockVCS(ctrl *gomock.Controller) *MockVCS {
	mock := &MockVCS{ctrl: ctrl}
	mock.recorder = &MockVCSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVCS) EXPECT() *MockVCSMockRecorder {
	return m.recorder
}

// CheckMergeability mocks base method.
func (m *MockVCS) CheckMergeability(ctx context.Context, req entity.MergeRequest) (entity.MergeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckMergeability", ctx, req)
	ret0, _ := ret[0].(entity.MergeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckMergeability indicates an expected call of CheckMergeability.
func (mr *MockVCSMockRecorder) CheckMergeability(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckMergeability", reflect.TypeOf((*MockVCS)(nil).CheckMergeability), ctx, req)
}

// Land mocks base method.
func (m *MockVCS) Land(ctx context.Context, req entity.MergeRequest) (entity.MergeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Land", ctx, req)
	ret0, _ := ret[0].(entity.MergeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Land indicates an expected call of Land.
func (mr *MockVCSMockRecorder) Land(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Land", reflect.TypeOf((*MockVCS)(nil).Land), ctx, req)
}

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
	isgomock struct{}
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// For mocks base method.
func (m *MockFactory) For(cfg vcs.Config) (vcs.VCS, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "For", cfg)
	ret0, _ := ret[0].(vcs.VCS)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// For indicates an expected call of For.
func (mr *MockFactoryMockRecorder) For(cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "For", reflect.TypeOf((*MockFactory)(nil).For), cfg)
}
